In [3]:
import numpy as np

In [2]:
#Create a 1D array of numbers from 0 to 9

In [10]:
Array_1d = np.array(range(10))
Array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Create a 3×3 numpy array of all True’s

In [11]:
Array_3d = np.ones((3,3),dtype = bool)
Array_3d

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
#Given an array as input, print only odd numbers as output

In [15]:
Array_odd = np.array(range(10))

In [16]:
Z = list(filter(lambda x: (x % 2 != 0), Array_odd))
Z

[1, 3, 5, 7, 9]

In [17]:
li = list(Array_odd)
Y = (list(filter(lambda x: (x % 2 != 0), Array_odd)),-2)
Y

([1, 3, 5, 7, 9], -2)

In [ ]:
Array_odd[0]

In [18]:
arr=np.array(range(10))
lis = list(arr)
type(lis)
for x in arr:
    if x%2!=0:
        print(-2)
    else:
        print(x)

    

0
-2
2
-2
4
-2
6
-2
8
-2


In [19]:
#Y = [x for x in arr if x%2==0 else -2 ]
#print(Y)
Z= [-2 if x%2!=0 else x for x in arr]
Z


[0, -2, 2, -2, 4, -2, 6, -2, 8, -2]

In [20]:
L = (lambda x:x%2!=0),arr
print(L)
New_L = list(filter(lambda x: (x%2 != 0) , arr))
print(New_L)

(<function <lambda> at 0x000002A90F322EA0>, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))
[1, 3, 5, 7, 9]


In [21]:
Array = np.array([[1,3],[4,5],[9,24]])

In [22]:
Array.shape

(3, 2)

In [23]:
Array.T

array([[ 1,  4,  9],
       [ 3,  5, 24]])

In [24]:
Array.T.shape

(2, 3)

In [25]:
Array1d = np.array([1,2,3,4])

In [26]:
Array2d = np.array([6,3,4,6])

In [27]:
np.vstack((Array1d,Array2d))

array([[1, 2, 3, 4],
       [6, 3, 4, 6]])

In [34]:
Array1d.shape
Array1d.size

4

In [40]:
a =np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
# Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 

In [43]:
a  = [1,2,3,4,5,6,7,8,9]

In [48]:
z = list(filter(lambda x:(x%2!=0),a))
z

[1, 3, 5, 7, 9]

In [49]:
y = list(filter(lambda i:(i%4==0),a))
y

[4, 8]

In [56]:
n = z +y

In [57]:
n

[1, 3, 5, 7, 9, 4, 8]

In [58]:
b = np.array(n)

In [59]:
b

array([1, 3, 5, 7, 9, 4, 8])

In [60]:
#Given array, check if there are any null values and print them out. 

In [66]:
Array_null = [[1,3],[2,None],[4,8],[None,7]]
Array_null

[[1, 3], [2, None], [4, 8], [None, 7]]

In [77]:
#for x,i in enumerate(Array_null):  

In [78]:
#How to find the count of each unique number in a NumPy array?

In [89]:
Array_unique = [1,1,3,4,5,6,7,8,4,3,4,3,4,3,2,2]
Uniquenum,Counts = np.unique(Array_unique,return_counts = True)
print(Uniquenum)
print(Counts)

[1 2 3 4 5 6 7 8]
[2 2 4 4 1 1 1 1]


In [90]:
#How to convert a numeric to a categorical (text) array?

In [91]:
Array = [1,2,3,4,6,7,8]

In [93]:
Array2 = np.array(Array,dtype = str)
print(Array2)

['1' '2' '3' '4' '6' '7' '8']


In [94]:
#Write a program to print all numbers between 99 and 299 which are either 
#divisible by 5 or 7. Exclude the elements which are divisible by both

In [111]:
ar_div = np.array(range(99,300))
z = []
for x in ar_div:
    if(x%5==0 or x%7==0):
        z.append(x)
for i in z:
    if (i%5==0 and i%7==0):
        z.remove(i)
print(z)             

[100, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 145, 147, 150, 154, 155, 160, 161, 165, 168, 170, 180, 182, 185, 189, 190, 195, 196, 200, 203, 205, 215, 217, 220, 224, 225, 230, 231, 235, 238, 240, 250, 252, 255, 259, 260, 265, 266, 270, 273, 275, 285, 287, 290, 294, 295]


In [1]:
#13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [37]:
Array_rev = np.arange(10)
Z = []
i=1
for i,x in enumerate(Array_rev,1):
    Z.append(Array_rev[-i])
Array_final = np.array(Z)
print(Array_final)

[9 8 7 6 5 4 3 2 1 0]
